server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DavidCamelo/config-properties.git
          clone-on-start: true
eureka:
  client:
    service-url:
      default-zone: eureka:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: zipkin:9411/api/v2/spans